name: CD - Deploy to Server

on:
  workflow_run:
    workflows: ["CI - Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Loyiha papkasiga o'tamiz
            cd /home/${{ secrets.SERVER_USER }}/repair-service

            # Yangi imijni tortib olamiz
            docker compose pull

            # Konteynerlarni yangilaymiz
            docker compose up -d

            # Eski va keraksiz imijni tozalaymiz
            docker image prune -f
